### ISSUE TITLE
Downloading multiple releases to the same output path results in error

### ISSUE THREAD

**Issue by bjornblissing** [i3h/download-release-asset#6]
If you run the script twice in sequence and specify the same output path for both executions will result in the following error:
```
      - name: Download release from source 1
        uses: i3h/download-release-asset@v1
        with:
          owner: owner1
          repo: test
          tag: v1.0.1
          file: v1.0.1.zip
          path: downloads
      
      - name: Download release from source 2
        uses: i3h/download-release-asset@v1
        with:
          owner: owner2
          repo: test
          tag: v2.0.4
          file: v2.0.4.zip
          path: downloads
```
Results in the following warning for the second release:

`Error: Command failed: mkdir downloads -ea 0`
